In [1]:
from sklearn.pipeline import Pipeline
## Features Scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [3]:
steps=[("Standard_scaler",StandardScaler()),
      ("classifier",LogisticRegression())]

In [4]:
steps

[('Standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [7]:
pipe=Pipeline(steps)

In [8]:
## Visualize Pipeline
from sklearn import set_config 

In [9]:
set_config(display="diagram")

In [10]:
pipe

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [11]:
## Creatting a dataset
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [12]:
X.shape

(1000, 20)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.33,random_state=42)



In [16]:
X_train

array([[-2.53587526, -0.08450199,  0.5033454 , ...,  1.30364772,
         0.74876898, -0.48673266],
       [ 0.28154736, -0.29604633, -1.08666915, ...,  1.26466241,
        -0.36321092, -1.12782422],
       [-0.37015827,  0.43605422,  1.28628037, ...,  1.52997796,
        -2.5499583 ,  0.28602676],
       ...,
       [-1.53252209,  2.16409968, -0.85802454, ..., -0.71804673,
         1.18799519, -1.01445087],
       [-0.61717553, -1.55868924, -0.57071273, ...,  0.95316015,
         1.13253277,  0.72080589],
       [-0.23811857, -0.39604814,  1.10919115, ..., -0.01012743,
        -0.93679926,  1.12803499]])

In [17]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [19]:
y_pred=pipe.predict(X_test)

In [20]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,

## Example-2
dispalying a pipeline with standard scaler, dimentionality reduction and the estimator 

In [22]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [24]:
steps=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]

In [26]:
pipe2=Pipeline(steps)

In [27]:
pipe2

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [29]:
pipe2['scaling'].fit_transform(X_train)

array([[-2.50803584, -0.09594152,  0.53884195, ...,  1.29550316,
         0.62115996, -0.40018702],
       [ 0.31676844, -0.30811323, -1.09947013, ...,  1.25736049,
        -0.29975426, -1.03247175],
       [-0.33664466,  0.42615844,  1.345559  , ...,  1.51694141,
        -2.11076429,  0.36195683],
       ...,
       [-1.50205388,  2.15932858, -0.86388031, ..., -0.68249357,
         0.98491623, -0.92065584],
       [-0.5843091 , -1.57450063, -0.56784126, ...,  0.95259117,
         0.93898363,  0.79076329],
       [-0.20425902, -0.4084116 ,  1.1630906 , ...,  0.01012448,
        -0.77478591,  1.1923982 ]])

In [30]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [31]:
pipe2.predict(X_test)

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,

## Complex examples of columns transformer

In [33]:
from sklearn.impute import SimpleImputer 

In [35]:
## numerical processing pipeline
import numpy as np
numeric_processor=Pipeline(
    steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy="mean")),
          ("scaler",StandardScaler())]

)


In [36]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [ ]:
## Categorical processing pipeline

In [39]:
## numerical processing pipeliZ
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    steps=[("imputation_constant",SimpleImputer(fill_value="missing",strategy="constant")),
          ("scaler",OneHotEncoder(handle_unknown="ignore"))]

)

In [40]:
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('scaler', OneHotEncoder(handle_unknown='ignore'))])

In [41]:
##  combine processing techniques
from sklearn.compose import ColumnTransformer

In [43]:
preprocessor=ColumnTransformer(
    [('categorical',categorical_processor,["gender","city"]),
    ('numerical',numeric_processor,['age','height'])]
)

In [44]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('scaler',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [45]:
from sklearn.pipeline import make_pipeline

In [52]:
pipe=make_pipeline(preprocessor,LogisticRegression())

In [53]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('scaler',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])